services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-project-template-dev
    command: sleep infinity
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - ..:/workspaces/workspace:cached
      - ${HOME}/.gitconfig:/home/vscode/.gitconfig_host
      - dind-var-lib-docker:/var/lib/docker
      - ${HOME}/.codex:/home/vscode/.codex:cached
      - ${HOME}/.config/gh:/home/vscode/.config/gh:cached
      - ${HOME}/.claude:/home/vscode/.claude:cached
      - ${HOME}/.claude.json:/home/vscode/.claude.json:cached

volumes:
  dind-var-lib-docker:
